configure.ac: Fix detecting sighandler_t on glibc
Fixes the following error/misdetection of sighandler_t:
```
config.log:2639:conftest.c:83:13: error: 'sighandler_t' undeclared (first use in this function); did you mean 'sa_handler'?
```

sighandler_t requires -D_GNU_SOURCE on glibc systems.

Signed-off-by: Sam James <sam@gentoo.org>